name: Deploy to Devsite

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      
      - name: Install npm dependencies
        run: npm install

      - name: Compile npm dependencies
        run: npm run build
      
      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --omit-dir-times --progress --no-perms --no-owner --delete -e "ssh -o StrictHostKeyChecking=no" --exclude='storage/' --exclude='bootstrap/' --exclude='.htaccess' --exclude='public/.htaccess' --exclude='.env' --exclude='.env.example' --exclude='.git/' --exclude='images/' --exclude='public/images/' --exclude='public/storage/' --exclude='public/fonts/' --exclude='public/plugins/' --exclude='public/users/' --exclude='public/web.config/' --exclude='resources/assets/custom_logos/' --exclude='server.php' --exclude='robots.txt'
          path: .
          remote_path: ${{ secrets.WORK_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}